### ISSUE TITLE
Google Map API key

### ISSUE THREAD

**Issue by ghost** [bitterendio/acf-field-type-mapmore#1]
Needs an input for a google API key

**Comment by rozklad** [comment]
That's right, we will add that

**Comment by stijn-de-witte** [comment]
Any update on this?

**Comment by rozklad** [comment]
@stijn-de-witte this repo was not mainted for long time, i've added hotfix to enable google api key to be set in 35f1ac3

After applying the update you will only need to add your API key via theme's functions.php like this:

```
function mapmore_acf_google_map_api() {

	acf_append_setting('mapmore_google_api_key', 'YOUR_GOOGLE_API_KEY');

}

add_filter('init', 'mapmore_acf_google_map_api');
```
